<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260922211235 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'add privileges';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE privilege (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, area_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_87209A875E237E06BD0F409C ON privilege (name, area_id)');
        $this->addSql('CREATE INDEX IDX_87209A87BD0F409C ON privilege (area_id)');
        $this->addSql('ALTER TABLE privilege ADD CONSTRAINT FK_87209A87BD0F409C FOREIGN KEY (area_id) REFERENCES area (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE privilege DROP CONSTRAINT FK_87209A87BD0F409C');
        $this->addSql('DROP TABLE privilege');
    }
}
