<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
use Override;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260217081636 extends AbstractMigration
{
    #[Override]
    public function getDescription(): string
    {
        return 'initial migration';
    }

    #[Override]
    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE card_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, is_print_ordered BOOLEAN NOT NULL, card_id VARCHAR(255) DEFAULT NULL, "user" INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CD1D625E356B3608 ON card_order ("user")');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, roles JSON NOT NULL, digital_card_id UUID NOT NULL, card_id VARCHAR(255) DEFAULT NULL, username VARCHAR(180) NOT NULL, display_name VARCHAR(255) NOT NULL, mail VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON "user" (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D6496A4E412A ON "user" (digital_card_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D6494ACC9A20 ON "user" (card_id)');
        $this->addSql('ALTER TABLE card_order ADD CONSTRAINT FK_CD1D625E356B3608 FOREIGN KEY ("user") REFERENCES "user" ("id") NOT DEFERRABLE');
    }

    #[Override]
    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE card_order DROP CONSTRAINT FK_CD1D625E356B3608');
        $this->addSql('DROP TABLE card_order');
        $this->addSql('DROP TABLE "user"');
    }
}
