<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260923233632 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'add privilege assignment';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE privilege_assignment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, user_id INT NOT NULL, privilege_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D2829EA76ED39532FB8AEA ON privilege_assignment (user_id, privilege_id)');
        $this->addSql('CREATE INDEX IDX_D2829EA76ED395 ON privilege_assignment (user_id)');
        $this->addSql('CREATE INDEX IDX_D2829E32FB8AEA ON privilege_assignment (privilege_id)');
        $this->addSql('ALTER TABLE privilege_assignment ADD CONSTRAINT FK_D2829EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE privilege_assignment ADD CONSTRAINT FK_D2829E32FB8AEA FOREIGN KEY (privilege_id) REFERENCES privilege (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE privilege_assignment DROP CONSTRAINT FK_D2829EA76ED395');
        $this->addSql('ALTER TABLE privilege_assignment DROP CONSTRAINT FK_D2829E32FB8AEA');
        $this->addSql('DROP TABLE privilege_assignment');
    }
}
