<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260922213217 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'add instruction assignments';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE instruction_assignment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, assigned_to_id INT NOT NULL, privilege_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_37D5022FF4BD7827 ON instruction_assignment (assigned_to_id)');
        $this->addSql('CREATE INDEX IDX_37D5022F32FB8AEA ON instruction_assignment (privilege_id)');
        $this->addSql('ALTER TABLE instruction_assignment ADD CONSTRAINT FK_37D5022FF4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE instruction_assignment ADD CONSTRAINT FK_37D5022F32FB8AEA FOREIGN KEY (privilege_id) REFERENCES privilege (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE instruction_assignment DROP CONSTRAINT FK_37D5022FF4BD7827');
        $this->addSql('ALTER TABLE instruction_assignment DROP CONSTRAINT FK_37D5022F32FB8AEA');
        $this->addSql('DROP TABLE instruction_assignment');
    }
}
