<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260930190911 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'add area ban';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE area_ban (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, area_id INT NOT NULL, user_id INT NOT NULL, banned_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F02E6859BD0F409CA76ED395 ON area_ban (area_id, user_id)');
        $this->addSql('CREATE INDEX IDX_F02E6859BD0F409C ON area_ban (area_id)');
        $this->addSql('CREATE INDEX IDX_F02E6859A76ED395 ON area_ban (user_id)');
        $this->addSql('CREATE INDEX IDX_F02E6859386B8E7 ON area_ban (banned_by_id)');
        $this->addSql('ALTER TABLE area_ban ADD CONSTRAINT FK_F02E6859BD0F409C FOREIGN KEY (area_id) REFERENCES area (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE area_ban ADD CONSTRAINT FK_F02E6859A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE area_ban ADD CONSTRAINT FK_F02E6859386B8E7 FOREIGN KEY (banned_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE area_ban DROP CONSTRAINT FK_F02E6859BD0F409C');
        $this->addSql('ALTER TABLE area_ban DROP CONSTRAINT FK_F02E6859A76ED395');
        $this->addSql('ALTER TABLE area_ban DROP CONSTRAINT FK_F02E6859386B8E7');
        $this->addSql('DROP TABLE area_ban');
    }
}
