<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260922212224 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'add instructions';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE instruction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7BBAE1565E237E06 ON instruction (name)');
        $this->addSql('CREATE TABLE instruction_privilege (instruction_id INT NOT NULL, privilege_id INT NOT NULL, PRIMARY KEY (instruction_id, privilege_id))');
        $this->addSql('CREATE INDEX IDX_FAA2168362A10F76 ON instruction_privilege (instruction_id)');
        $this->addSql('CREATE INDEX IDX_FAA2168332FB8AEA ON instruction_privilege (privilege_id)');
        $this->addSql('ALTER TABLE instruction_privilege ADD CONSTRAINT FK_FAA2168362A10F76 FOREIGN KEY (instruction_id) REFERENCES instruction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE instruction_privilege ADD CONSTRAINT FK_FAA2168332FB8AEA FOREIGN KEY (privilege_id) REFERENCES privilege (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE instruction_privilege DROP CONSTRAINT FK_FAA2168362A10F76');
        $this->addSql('ALTER TABLE instruction_privilege DROP CONSTRAINT FK_FAA2168332FB8AEA');
        $this->addSql('DROP TABLE instruction');
        $this->addSql('DROP TABLE instruction_privilege');
    }
}
