<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260922192520 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'add category bans';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE category_ban (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, lifted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, reason TEXT DEFAULT NULL, lifted_by INT DEFAULT NULL, "user" INT NOT NULL, category_id INT NOT NULL, created_by INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_473C7DBF174BDADF ON category_ban (lifted_by)');
        $this->addSql('CREATE INDEX IDX_473C7DBF356B3608 ON category_ban ("user")');
        $this->addSql('CREATE INDEX IDX_473C7DBF12469DE2 ON category_ban (category_id)');
        $this->addSql('CREATE INDEX IDX_473C7DBFDE12AB56 ON category_ban (created_by)');
        $this->addSql('ALTER TABLE category_ban ADD CONSTRAINT FK_473C7DBF174BDADF FOREIGN KEY (lifted_by) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE category_ban ADD CONSTRAINT FK_473C7DBF356B3608 FOREIGN KEY ("user") REFERENCES "user" ("id") NOT DEFERRABLE');
        $this->addSql('ALTER TABLE category_ban ADD CONSTRAINT FK_473C7DBF12469DE2 FOREIGN KEY (category_id) REFERENCES machine_category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE category_ban ADD CONSTRAINT FK_473C7DBFDE12AB56 FOREIGN KEY (created_by) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE category_ban DROP CONSTRAINT FK_473C7DBF174BDADF');
        $this->addSql('ALTER TABLE category_ban DROP CONSTRAINT FK_473C7DBF356B3608');
        $this->addSql('ALTER TABLE category_ban DROP CONSTRAINT FK_473C7DBF12469DE2');
        $this->addSql('ALTER TABLE category_ban DROP CONSTRAINT FK_473C7DBFDE12AB56');
        $this->addSql('DROP TABLE category_ban');
    }
}
