<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260922192214 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'add einweisung attendances and user privileges';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE instruction_attendance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, date DATE NOT NULL, "user" INT NOT NULL, instruction_id INT NOT NULL, confirmed_by INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6AF34B04356B3608 ON instruction_attendance ("user")');
        $this->addSql('CREATE INDEX IDX_6AF34B0462A10F76 ON instruction_attendance (instruction_id)');
        $this->addSql('CREATE INDEX IDX_6AF34B04FB3F81CB ON instruction_attendance (confirmed_by)');
        $this->addSql('CREATE TABLE user_privilege (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "user" INT NOT NULL, privilege_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_87C01763356B3608 ON user_privilege ("user")');
        $this->addSql('CREATE INDEX IDX_87C0176332FB8AEA ON user_privilege (privilege_id)');
        $this->addSql('CREATE TABLE user_privilege_instruction_attendance (user_privilege_id INT NOT NULL, instruction_attendance_id INT NOT NULL, PRIMARY KEY (user_privilege_id, instruction_attendance_id))');
        $this->addSql('CREATE INDEX IDX_33C1F42DB237F6E8 ON user_privilege_instruction_attendance (user_privilege_id)');
        $this->addSql('CREATE INDEX IDX_33C1F42D567158EE ON user_privilege_instruction_attendance (instruction_attendance_id)');
        $this->addSql('ALTER TABLE instruction_attendance ADD CONSTRAINT FK_6AF34B04356B3608 FOREIGN KEY ("user") REFERENCES "user" ("id") NOT DEFERRABLE');
        $this->addSql('ALTER TABLE instruction_attendance ADD CONSTRAINT FK_6AF34B0462A10F76 FOREIGN KEY (instruction_id) REFERENCES instruction (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE instruction_attendance ADD CONSTRAINT FK_6AF34B04FB3F81CB FOREIGN KEY (confirmed_by) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_privilege ADD CONSTRAINT FK_87C01763356B3608 FOREIGN KEY ("user") REFERENCES "user" ("id") NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_privilege ADD CONSTRAINT FK_87C0176332FB8AEA FOREIGN KEY (privilege_id) REFERENCES privilege (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_privilege_instruction_attendance ADD CONSTRAINT FK_33C1F42DB237F6E8 FOREIGN KEY (user_privilege_id) REFERENCES user_privilege (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_privilege_instruction_attendance ADD CONSTRAINT FK_33C1F42D567158EE FOREIGN KEY (instruction_attendance_id) REFERENCES instruction_attendance (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE instruction_attendance DROP CONSTRAINT FK_6AF34B04356B3608');
        $this->addSql('ALTER TABLE instruction_attendance DROP CONSTRAINT FK_6AF34B0462A10F76');
        $this->addSql('ALTER TABLE instruction_attendance DROP CONSTRAINT FK_6AF34B04FB3F81CB');
        $this->addSql('ALTER TABLE user_privilege DROP CONSTRAINT FK_87C01763356B3608');
        $this->addSql('ALTER TABLE user_privilege DROP CONSTRAINT FK_87C0176332FB8AEA');
        $this->addSql('ALTER TABLE user_privilege_instruction_attendance DROP CONSTRAINT FK_33C1F42DB237F6E8');
        $this->addSql('ALTER TABLE user_privilege_instruction_attendance DROP CONSTRAINT FK_33C1F42D567158EE');
        $this->addSql('DROP TABLE instruction_attendance');
        $this->addSql('DROP TABLE user_privilege');
        $this->addSql('DROP TABLE user_privilege_instruction_attendance');
    }
}
