<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260924193505 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'add privileges in specific areas to assign to users via instructions or directly';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE area (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D7943D685E237E06 ON area (name)');
        $this->addSql('CREATE TABLE instruction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7BBAE1565E237E06 ON instruction (name)');
        $this->addSql('CREATE TABLE instruction_privilege (instruction_id INT NOT NULL, privilege_id INT NOT NULL, PRIMARY KEY (instruction_id, privilege_id))');
        $this->addSql('CREATE INDEX IDX_FAA2168362A10F76 ON instruction_privilege (instruction_id)');
        $this->addSql('CREATE INDEX IDX_FAA2168332FB8AEA ON instruction_privilege (privilege_id)');
        $this->addSql('CREATE TABLE privilege (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, area_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_87209A875E237E06BD0F409C ON privilege (name, area_id)');
        $this->addSql('CREATE INDEX IDX_87209A87BD0F409C ON privilege (area_id)');
        $this->addSql('CREATE TABLE privilege_assignment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, user_id INT NOT NULL, privilege_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D2829EA76ED39532FB8AEA ON privilege_assignment (user_id, privilege_id)');
        $this->addSql('CREATE INDEX IDX_D2829EA76ED395 ON privilege_assignment (user_id)');
        $this->addSql('CREATE INDEX IDX_D2829E32FB8AEA ON privilege_assignment (privilege_id)');
        $this->addSql('ALTER TABLE instruction_privilege ADD CONSTRAINT FK_FAA2168362A10F76 FOREIGN KEY (instruction_id) REFERENCES instruction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE instruction_privilege ADD CONSTRAINT FK_FAA2168332FB8AEA FOREIGN KEY (privilege_id) REFERENCES privilege (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE privilege ADD CONSTRAINT FK_87209A87BD0F409C FOREIGN KEY (area_id) REFERENCES area (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE privilege_assignment ADD CONSTRAINT FK_D2829EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE privilege_assignment ADD CONSTRAINT FK_D2829E32FB8AEA FOREIGN KEY (privilege_id) REFERENCES privilege (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE instruction_privilege DROP CONSTRAINT FK_FAA2168362A10F76');
        $this->addSql('ALTER TABLE instruction_privilege DROP CONSTRAINT FK_FAA2168332FB8AEA');
        $this->addSql('ALTER TABLE privilege DROP CONSTRAINT FK_87209A87BD0F409C');
        $this->addSql('ALTER TABLE privilege_assignment DROP CONSTRAINT FK_D2829EA76ED395');
        $this->addSql('ALTER TABLE privilege_assignment DROP CONSTRAINT FK_D2829E32FB8AEA');
        $this->addSql('DROP TABLE area');
        $this->addSql('DROP TABLE instruction');
        $this->addSql('DROP TABLE instruction_privilege');
        $this->addSql('DROP TABLE privilege');
        $this->addSql('DROP TABLE privilege_assignment');
    }
}
