<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260922192105 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'add machine categories and privileges';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE machine_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CD2BD5DD5E237E06 ON machine_category (name)');
        $this->addSql('CREATE TABLE privilege (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, validity_months INT DEFAULT NULL, description TEXT DEFAULT NULL, name VARCHAR(255) NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_87209A8712469DE2 ON privilege (category_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_87209A8712469DE25E237E06 ON privilege (category_id, name)');
        $this->addSql('ALTER TABLE privilege ADD CONSTRAINT FK_87209A8712469DE2 FOREIGN KEY (category_id) REFERENCES machine_category (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE privilege DROP CONSTRAINT FK_87209A8712469DE2');
        $this->addSql('DROP TABLE machine_category');
        $this->addSql('DROP TABLE privilege');
    }
}
